
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[436] =
    {   0,
        0,    0,   76,   74,   67,   67,   74,    8,   74,    8,
       69,    8,    8,    8,    8,   74,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,    8,   67,    7,   68,   73,    0,   69,
        1,    3,    5,    2,    0,   71,    0,   72,   70,    0,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   48,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       70,   70,   70,    6,   73,    4,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   62,   70,
       70,   70,   70,   70,   29,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   45,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       64,   70,   70,   70,   70,   70,   70,   70,   28,   52,
       26,   25,   70,   70,   70,   70,   50,   70,   70,   70,
       70,   70,   70,   70,   70,    0,    0,    0,   70,   70,
       70,    0,   47,   70,   30,   70,   70,   70,   70,   70,

       49,    9,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       10,   70,   70,    0,   70,   70,   33,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   23,   70,   70,   70,   70,   70,   70,   70,   59,
       70,   70,   70,   70,   70,   70,   70,   11,   44,   43,
       70,   70,   70,   70,   70,   70,   70,   31,   70,   70,
       70,   70,   70,   70,   27,    0,   51,   70,   70,   70,
       70,   70,   70,   70,   70,   60,   56,   63,    0,   32,
       70,   70,   14,   70,   70,    0,   70,   42,   70,   13,

        0,   70,   41,   46,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   58,   70,   70,   70,   70,   70,    0,
       15,   70,   12,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   57,   70,   66,   70,   54,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   53,   70,
       70,   70,   70,   70,   70,   55,   70,   70,   70,   70,
       70,   16,   70,   70,   36,   70,   24,   70,   70,   70,
       70,    0,   61,   65,   70,   70,   70,   70,    0,   37,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   17,   70,   34,   70,   70,   40,   70,   70,

       35,   70,   39,    0,   70,   70,   70,   38,   70,   70,
       70,   22,   70,   70,   70,   70,   70,   70,   70,   20,
       70,   70,   70,   70,   21,   70,   70,   70,   19,   70,
       70,   70,   70,   18,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    1,    1,    6,    1,    6,    7,    6,
        6,    6,    6,    6,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    6,    6,   12,
       13,   14,   15,   16,   17,   18,   17,   19,   20,   17,
       21,   17,   17,   17,   22,   17,   23,   24,   17,   25,
       17,   17,   17,   17,   26,   17,   27,   17,   17,   17,
        6,    1,    6,    6,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   38,   17,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,    6,    6,    6,   54,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    2,    1,    1,    3,    4,    1,    1,
        4,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1
    } ;

static yyconst flex_uint16_t yy_base[440] =
    {   0,
        0,    0,  170, 2077,   53,   56,  154, 2077,  143,  134,
       52,  130,   51,  125,   54,   58,   60,   62,   64,   66,
       68,   70,   72,   76,   95,   98,  100,  103,  114,  117,
      122,  133,  140,  145,  155,  158,  150,  167,  169,  173,
      186,  195,  199,  122,  110, 2077,  121,    0,  116,   76,
       79, 2077, 2077, 2077,   81,   91,  108,  143, 2077,  197,
      203,  205,  213,  221,  229,  232,  239,  245,  247,  254,
      258,  264,  272,  269,  291,  294,  296,  280,  299,  305,
      309,  327,  335,  337,  340,  342,  346,  349,  364,  353,
      368,  376,  379,  390,  394,  401,  408,  403,  412,  419,

      426,  434,  445, 2077,    0, 2077,  448,  450,  453,  458,
      462,  464,  467,  489,  491,  494,  496,  499,  502,  505,
      524,  527,  532,  535,  537,  546,  543,  539,  541,  549,
      551,  574,  576,  579,  581,  584,  590,  592,  608,  614,
      617,  620,  623,  626,  631,  633,  636,  649,  655,  658,
      660,  663,  667,  672,  682,  685,  689,  691,  704,  716,
      718,  722,  726,  730,  728,  740,  732,  744,  757,  759,
      762,  768,  770,  776,  781,  784,  786,  792,  794,  798,
      800,  803,  822,  826,  808,  833,  835,  841,  837,  848,
      850,  852,  859,  874,  876,  878,  884,  889,  892,  902,

      906,  917,  919,  924,  929,  933,  935,  942,  946,  948,
      952,  959,  970,  974,  976,  986,  978,  988,  992, 1000,
     1002, 1011, 1014, 1016, 1019, 1024, 1027, 1030, 1033, 1041,
     1058, 1060, 1063, 1069, 1071, 1075, 1086, 1088, 1093, 1099,
     1104, 1110, 1115, 1118, 1122, 1129, 1132, 1140, 1154, 1156,
     1158, 1162, 1164, 1167, 1170, 1173, 1180, 1186, 1199, 1202,
     1204, 1208, 1211, 1215, 1218, 1226, 1221, 1230, 1233, 1240,
     1244, 1255, 1257, 1263, 1266, 1272, 1282, 1285, 1290, 1296,
     1300, 1304, 1308, 1312, 1314, 1318, 1323, 1336, 1340, 1342,
     1345, 1349, 1353, 1358, 1364, 1371, 1381, 1383, 1386, 1393,

     1395, 1399, 1408, 1410, 1418, 1423, 1425, 1427, 1432, 1434,
     1440, 1436, 1442, 1451, 1464, 1467, 1477, 1479, 1483, 1491,
     1495, 1501, 1505, 1508, 1513, 1523, 1527, 1530, 1532, 1542,
     1545, 1549, 1554, 1560, 1571, 1573, 1576, 1578, 1582, 1587,
     1601, 1604, 1606, 1610, 1612, 1614, 1616, 1618, 1623, 1628,
     1645, 1647, 1650, 1660, 1654, 1657, 1662, 1664, 1669, 1686,
     1672, 1688, 1691, 1697, 1699, 1701, 1703, 1705, 1714, 1729,
     1731, 1733, 1736, 1739, 1741, 1743, 1746, 1758, 1765, 1770,
     1773, 1780, 1782, 1784, 1788, 1796, 1799, 1810, 1812, 1814,
     1821, 1826, 1828, 1836, 1840, 1850, 1852, 1855, 1858, 1863,

     1867, 1869, 1874, 1880, 1885, 1891, 1893, 1896, 1899, 1907,
     1910, 1915, 1926, 1932, 1934, 1937, 1939, 1943, 1951, 1961,
     1970, 1973, 1978, 1980, 1983, 1985, 1987, 1995, 1992, 2009,
     2019, 2021, 2024, 2027, 2077,   87,   77, 2068, 2072
    } ;

static yyconst flex_int16_t yy_def[440] =
    {   0,
      435,    1,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  436,  437,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  435,  435,  435,  435,  439,  435,  435,
      435,  435,  435,  435,  436,  436,  437,  437,  435,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  435,  439,  435,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,    0,  435,  435,  435,  435
    } ;

static yyconst flex_uint16_t yy_nxt[2132] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,    8,   28,   29,
       30,   31,   32,   33,   17,   34,   35,   17,   36,   37,
       38,   39,   40,   17,   41,   42,   43,   17,   17,   17,
       17,   17,   17,   44,   45,   45,   45,   45,   45,   45,
       49,   55,   50,   52,   53,   57,   59,   60,   59,   60,
       59,   60,   59,   60,   59,   60,   59,   60,   59,   60,
       58,   55,   59,   60,   49,   57,   50,   60,   55,   60,
       56,   60,  106,   60,   62,   60,   65,   60,   55,   60,

       63,   59,   60,   60,   59,   60,   59,   60,   55,   59,
       60,   45,   45,   45,   66,   57,   64,   68,   55,   67,
       59,   60,   60,   59,   60,   60,   47,   60,   59,   60,
       60,   47,   71,   72,  104,   57,   69,   54,   70,   59,
       60,   60,   51,   48,   60,   74,   59,   60,   75,   60,
       57,   59,   60,   47,   77,   73,   59,   60,   78,   76,
       60,   59,   60,   79,   59,   60,   46,   60,   82,  435,
       57,   80,   60,   59,   60,   59,   60,   60,   88,   59,
       60,   83,   60,   81,  435,   60,   84,  435,   85,  435,
       87,  435,   59,   60,   60,   86,   60,  435,   91,   89,

       60,   59,   60,  435,   60,   59,   60,  435,   90,   59,
       60,   59,   60,   60,   93,   92,  435,   94,   96,   59,
       60,   95,   60,  435,   60,  435,   60,   59,   60,  435,
       60,  100,   60,  435,  101,   59,   60,  435,   59,   60,
       60,   97,   98,  102,   99,   59,   60,  435,   60,  107,
      103,   59,   60,   59,   60,  435,   60,  108,  109,   60,
       59,   60,  435,  110,   59,   60,   60,  435,  111,  435,
       59,   60,   60,  112,   60,   59,   60,  113,   59,   60,
      435,   60,  435,  115,  435,   60,   59,   60,  435,  114,
      116,   60,  435,  435,  117,  435,   60,   59,   60,   60,

       59,   60,   59,   60,  435,   59,   60,   60,  435,  435,
      118,   59,   60,  119,  120,   59,   60,  435,   60,  435,
      435,   60,  435,   60,  121,  125,   60,  122,  435,  123,
      435,  435,   60,   59,   60,  435,   60,  435,  126,  435,
      124,   59,   60,   59,   60,  128,   59,   60,   59,   60,
      127,  129,   59,   60,   60,   59,   60,  435,  435,   59,
       60,  435,   60,  435,   60,  130,  435,   60,  435,   60,
       59,   60,  435,   60,   59,   60,   60,  435,  133,  131,
       60,  132,   59,   60,  435,   59,   60,  134,  135,  435,
      435,   60,  435,  139,  136,   60,   59,   60,  138,  137,

       59,   60,  435,   60,  435,  140,   60,   59,   60,   59,
       60,  142,  435,  141,   59,   60,  435,   60,   59,   60,
      435,   60,  145,  435,  143,   59,   60,  435,   60,  146,
       60,  144,   59,   60,  435,   60,  149,  435,  435,   60,
       59,   60,  150,  435,  147,  435,   60,  435,  151,  435,
      148,   59,   60,   60,   59,   60,   59,   60,  153,   59,
       60,   60,  435,  152,   59,   60,  435,  435,   59,   60,
       59,   60,   60,   59,   60,   60,  435,   60,  157,  435,
       60,  154,  435,  159,  435,   60,  158,  155,  156,   60,
      161,   60,  435,  435,   60,   59,   60,   59,   60,  160,

       59,   60,   59,   60,  162,   59,   60,  435,   59,   60,
      435,   59,   60,  163,  435,  435,   60,  435,   60,  435,
      435,   60,  435,   60,  435,  167,   60,  166,  164,   60,
       59,   60,   60,   59,   60,  168,  165,  170,   59,   60,
      169,   59,   60,   59,   60,   59,   60,   59,   60,   59,
       60,   60,   59,   60,   60,   59,   60,   59,   60,   60,
      173,  435,   60,  435,   60,  435,   60,  175,   60,  171,
       60,  174,  172,   60,  176,  177,   60,  435,   60,  180,
       59,   60,   59,   60,  178,   59,   60,   59,   60,  435,
       59,   60,  435,  435,  179,  435,   59,  186,   59,  187,

      435,   60,  435,   60,  435,  435,   60,  435,   60,  435,
      181,   60,  435,  184,   59,  188,  185,   60,  435,   60,
       59,   60,  182,   59,   60,  183,   59,   60,  435,   59,
      192,  435,   59,   60,  435,   60,  435,   59,   60,   59,
       60,   60,   59,   60,   60,  435,  189,   60,  435,  190,
       60,  435,  191,   60,  435,   59,   60,  193,   60,  435,
       60,   59,   60,   60,   59,   60,   59,   60,  435,   59,
       60,  195,  435,   59,   60,  194,   60,  197,   59,   60,
      435,  435,   60,  196,  435,   60,  435,   60,   59,   60,
       60,   59,   60,  435,   60,   59,   60,   59,   60,   60,

      435,  198,  200,  435,  202,  435,  199,  201,  435,   60,
       59,   60,   60,  435,  203,  435,   60,  435,   60,  205,
      435,  206,   59,   60,   59,   60,  204,  435,   59,   60,
      435,   60,   59,   60,   59,   60,   59,   60,   59,   60,
      209,  435,  435,   60,  435,   60,   59,   60,  207,   60,
       59,   60,  435,   60,  435,   60,  208,   60,  211,   60,
      435,  435,  210,   59,   60,   59,   60,   60,   59,   60,
      435,   60,  435,  212,   59,   60,   59,   60,  435,  214,
      435,  213,   59,   60,   60,  215,   60,   59,   60,   60,
       59,   60,   59,   60,  435,   60,  435,   60,   59,   60,

       59,   60,  435,   60,   59,   60,   59,   60,   60,   59,
      224,   60,  435,   60,   59,   60,  435,  216,  435,   60,
      219,   60,  218,  435,  217,   60,  221,   60,   59,   60,
       60,  435,   59,   60,  435,   60,  222,  435,  220,  435,
       60,  435,   60,   59,   60,  435,  227,  435,   60,   60,
      225,  435,  223,   60,   59,   60,   59,   60,  435,   60,
       60,  435,   60,  435,   60,   59,   60,  231,   60,  435,
      226,  229,  435,  228,  230,   60,  435,   60,  435,   60,
       59,   60,   59,   60,   59,   60,   60,  435,  234,  435,
       59,   60,  232,  435,  233,   59,   60,  435,   59,   60,

      435,   60,  435,   60,  435,   60,  235,  435,   59,   60,
      236,   60,   59,   60,  237,  435,   60,  435,  435,   60,
      435,  239,  240,   59,   60,   59,   60,  435,  238,   60,
       59,   60,  435,   60,  435,   59,   60,  435,  241,   59,
       60,   59,   60,  435,   60,  435,   60,  244,   59,   60,
      435,   60,   59,   60,   59,   60,   60,  435,   59,   60,
       60,  435,   60,  435,  242,   59,   60,  246,  245,   60,
      435,  243,  435,   60,  247,   60,   59,   60,  248,   60,
       59,   60,   59,   60,   59,   60,   60,  435,  249,  435,
      250,  435,   59,   60,   59,   60,  435,   60,   59,   60,

      251,   60,  435,   60,  435,   60,   59,   60,   59,   60,
      256,  435,  253,   60,  252,   60,  254,   59,   60,   60,
       59,   60,  435,   60,  255,   59,   60,   60,  435,   60,
       59,   60,  258,   59,   60,  257,   59,   60,   60,   59,
       60,   60,  435,   60,  435,  259,   60,   59,   60,  260,
      435,   60,  435,  435,   60,  261,  435,   60,  435,  263,
       60,  262,  435,  264,   59,   60,   59,   60,   60,   59,
       60,  265,  435,  266,  435,   59,   60,   59,   60,  267,
      435,   59,   60,  435,  435,   60,  435,   60,  435,  435,
       60,  435,   59,   60,   59,   60,   60,  435,   60,   59,

      276,  272,   60,  273,  268,   59,   60,  435,  269,  271,
       59,   60,  270,   60,  435,   60,   59,   60,  435,  275,
       60,   59,   60,  435,   59,   60,   60,  435,   59,   60,
      274,   60,  435,  435,  277,   59,   60,   60,   59,   60,
      435,  435,   60,  435,  278,   60,   59,   60,  435,   60,
      280,  435,  435,  279,  281,  435,   60,  435,  435,   60,
       59,   60,   59,   60,   59,   60,  435,   60,   59,   60,
       59,   60,  283,   59,  289,  282,   59,   60,  284,   59,
       60,   60,  435,   60,  435,   60,   59,   60,  435,   60,
      435,   60,   59,   60,   60,  285,  435,   60,  286,  435,

       60,  287,  288,  435,  291,   59,   60,   60,   59,   60,
       59,   60,  435,   60,   59,   60,  290,   59,   60,  435,
      292,   59,  296,  435,   59,   60,   60,   59,   60,   60,
      435,   60,   59,   60,  435,   60,   59,   60,   60,   59,
      301,  295,   60,  435,  293,   60,   59,   60,   60,  435,
       59,   60,  435,   60,  294,  435,  435,   60,  297,  298,
       60,   59,   60,   59,   60,  435,  435,   60,  299,   59,
       60,   60,   59,   60,  435,  300,  302,  303,  435,   60,
      435,  435,   60,  435,   60,  435,  305,  435,   59,   60,
       60,   59,   60,   60,  435,  306,   59,   60,  435,   60,

      307,  304,   59,   60,  435,  308,   59,   60,  309,   60,
       59,   60,   60,  310,   59,   60,  435,   60,   59,   60,
       59,   60,  435,   60,   59,   60,  435,   60,  311,   59,
       60,   60,  435,  435,  312,   60,  314,  435,  313,   60,
      435,   60,   59,   60,  435,   60,  435,   60,   59,   60,
       60,   59,  320,  317,  315,   59,   60,  435,  316,   59,
       60,  435,  435,   60,   59,   60,  435,   60,  435,   60,
       59,   60,   60,  318,  435,  435,   60,  435,   60,  435,
       60,  435,  319,  435,  435,   60,  322,   59,   60,   59,
       60,   60,   59,   60,  435,  321,  323,  435,   60,   59,

       60,  435,   60,  435,  324,   59,   60,  435,   60,  435,
       60,  435,  325,   60,   59,   60,   59,   60,  326,  435,
       60,  435,   60,  435,   59,   60,   60,  435,  327,   59,
       60,   59,   60,   59,   60,   60,  435,   60,   59,   60,
       59,   60,   59,   60,  328,   60,   59,   60,   59,   60,
       60,  435,   60,  435,   60,  331,  329,   59,   60,   60,
      435,   60,  330,   60,  435,  332,  435,   60,  435,   60,
       59,   60,  333,   59,   60,  435,  335,  435,   60,  435,
      334,  435,  336,   59,   60,   59,   60,  435,  337,   59,
       60,   60,  435,  435,   60,  339,  435,  435,   60,  435,

      338,   59,   60,  435,   60,  435,   60,   59,   60,  435,
       60,   59,   60,  340,   59,   60,  435,  341,   60,   59,
       60,  435,   60,  435,  343,  435,  435,  342,   60,   59,
       60,  435,   60,   59,   60,   60,   59,   60,   59,   60,
       60,  435,  435,  435,  435,  346,  345,  344,   59,   60,
       60,   59,   60,  435,   60,   59,   60,   60,  435,   60,
       59,   60,  349,  347,  350,  348,   59,   60,  435,   60,
      435,  435,   60,  435,  351,  435,   60,   59,   60,   59,
       60,   60,   59,   60,   59,   60,  435,   60,   59,   60,
      435,  352,  355,   59,   60,  435,  353,  435,   60,  435,

       60,  356,  354,   60,  435,   60,  357,   59,   60,   60,
       59,   60,   59,   60,   60,  358,   59,   60,   59,   60,
       59,   60,   59,   60,   59,   60,  435,  435,   60,   59,
       60,   60,  435,   60,   59,   60,  360,   60,  435,   60,
      435,   60,  362,   60,  361,   60,  435,  364,  359,  435,
       60,   59,   60,   59,   60,   60,   59,   60,  435,  363,
       59,  372,  365,   59,   60,  366,   59,   60,   59,   60,
       59,   60,   60,  367,   60,   59,   60,   60,   59,   60,
      435,   60,  370,  369,   60,  368,  435,   60,  371,   60,
      435,   60,   59,   60,   59,   60,   60,   59,   60,   60,

      373,  375,  374,   59,  379,   59,   60,   59,   60,   59,
       60,   59,   60,   60,  435,   60,  376,  435,   60,  377,
       59,   60,  435,  378,   60,  435,   60,  435,   60,  435,
       60,  435,   60,  381,  435,   59,   60,   59,   60,  435,
       60,   60,   59,   60,  380,   59,   60,   59,   60,   59,
       60,  382,   59,   60,  435,  383,   60,  435,   60,  435,
       60,  435,  435,   60,   59,   60,   60,  435,   60,  384,
       60,  435,   60,   60,  435,  385,   59,   60,  389,   59,
       60,  387,  386,  435,  388,   60,   59,   60,   59,   60,
       59,   60,   60,  391,   59,   60,  435,   60,  390,  435,

       60,  435,   59,   60,  435,   59,   60,   60,  435,   60,
      435,   60,  435,  392,  435,   60,   59,   60,   59,   60,
       59,   60,  394,   60,  396,  393,   60,   59,   60,  435,
      395,  397,   59,   60,   59,   60,  435,   60,  435,   60,
      435,   60,   59,  404,  435,  398,   59,   60,   60,  435,
      399,  402,  400,   60,  435,   60,   59,   60,   59,   60,
      401,   59,   60,   60,   59,   60,  435,   60,  435,   59,
       60,  435,  403,   59,   60,   59,   60,   60,  405,   60,
       59,   60,   60,  435,  406,   60,  435,   60,  435,  407,
       60,   59,   60,  435,   60,  435,   60,   59,   60,   59,

       60,   60,   59,   60,  435,   59,   60,   60,  435,  408,
      410,  435,   60,   59,   60,  409,   59,   60,   60,  435,
       60,   59,   60,   60,  435,  411,   60,  435,  435,  413,
      435,  412,   59,   60,   60,  414,  435,   60,   59,   60,
       59,   60,   60,   59,   60,   59,   60,  435,  415,   59,
       60,  435,  435,   60,  435,  435,  416,   59,   60,   60,
      435,   60,  435,  435,   60,  435,   60,   59,   60,  435,
       60,  435,  417,  418,  419,  421,   59,   60,   60,   59,
       60,  435,  420,  422,   59,   60,   59,   60,   60,   59,
       60,   59,   60,   59,   60,  435,  423,   60,   59,   60,

       60,   59,   60,  435,  435,   60,  435,   60,  435,  435,
       60,  424,   60,  435,   60,   59,   60,  435,  425,   60,
      427,  435,   60,  430,  426,   59,   60,   59,   60,  428,
       59,   60,  429,   59,   60,  435,   60,  435,  435,  435,
      435,  435,  435,  435,  435,  431,   60,  435,   60,  435,
      435,   60,  435,  435,   60,  435,  435,  435,  435,  432,
      435,  435,  435,  435,  435,  435,  435,  433,  435,  434,
       61,   61,  105,  435,  105,  105,    3,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435
    } ;

static yyconst flex_int16_t yy_chk[2132] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    6,    6,    6,
       11,   15,   11,   13,   13,   16,   17,   17,   18,   18,
       19,   19,   20,   20,   21,   21,   22,   22,   23,   23,
      437,   15,   24,   24,   50,   16,   50,   17,   55,   18,
      436,   19,   51,   20,   18,   21,   21,   22,   56,   23,

       19,   25,   25,   24,   26,   26,   27,   27,   55,   28,
       28,   45,   45,   45,   22,   57,   20,   24,   56,   23,
       29,   29,   25,   30,   30,   26,   49,   27,   31,   31,
       28,   47,   27,   28,   44,   57,   25,   14,   26,   32,
       32,   29,   12,   10,   30,   30,   33,   33,   30,   31,
       58,   34,   34,    9,   31,   29,   37,   37,   31,   30,
       32,   35,   35,   31,   36,   36,    7,   33,   33,    3,
       58,   32,   34,   38,   38,   39,   39,   37,   37,   40,
       40,   33,   35,   32,    0,   36,   34,    0,   35,    0,
       36,    0,   41,   41,   38,   35,   39,    0,   39,   38,

       40,   42,   42,   60,   60,   43,   43,    0,   38,   61,
       61,   62,   62,   41,   40,   39,    0,   40,   41,   63,
       63,   40,   42,    0,   60,    0,   43,   64,   64,    0,
       61,   43,   62,    0,   43,   65,   65,    0,   66,   66,
       63,   42,   42,   43,   42,   67,   67,    0,   64,   62,
       43,   68,   68,   69,   69,    0,   65,   63,   63,   66,
       70,   70,    0,   64,   71,   71,   67,    0,   65,    0,
       72,   72,   68,   66,   69,   74,   74,   67,   73,   73,
        0,   70,    0,   69,    0,   71,   78,   78,    0,   68,
       70,   72,    0,    0,   71,    0,   74,   75,   75,   73,

       76,   76,   77,   77,    0,   79,   79,   78,    0,    0,
       72,   80,   80,   73,   74,   81,   81,    0,   75,    0,
        0,   76,    0,   77,   75,   78,   79,   76,    0,   77,
        0,    0,   80,   82,   82,    0,   81,    0,   79,    0,
       77,   83,   83,   84,   84,   81,   85,   85,   86,   86,
       80,   81,   87,   87,   82,   88,   88,    0,    0,   90,
       90,    0,   83,    0,   84,   82,    0,   85,    0,   86,
       89,   89,    0,   87,   91,   91,   88,    0,   86,   83,
       90,   84,   92,   92,    0,   93,   93,   86,   86,    0,
        0,   89,    0,   90,   87,   91,   94,   94,   89,   88,

       95,   95,    0,   92,    0,   91,   93,   96,   96,   98,
       98,   92,    0,   91,   97,   97,    0,   94,   99,   99,
        0,   95,   95,    0,   93,  100,  100,    0,   96,   96,
       98,   94,  101,  101,    0,   97,   97,    0,    0,   99,
      102,  102,   98,    0,   96,    0,  100,    0,   99,    0,
       96,  103,  103,  101,  107,  107,  108,  108,  101,  109,
      109,  102,    0,  100,  110,  110,    0,    0,  111,  111,
      112,  112,  103,  113,  113,  107,    0,  108,  108,    0,
      109,  102,    0,  109,    0,  110,  108,  103,  107,  111,
      111,  112,    0,    0,  113,  114,  114,  115,  115,  110,

      116,  116,  117,  117,  112,  118,  118,    0,  119,  119,
        0,  120,  120,  113,    0,    0,  114,    0,  115,    0,
        0,  116,    0,  117,    0,  117,  118,  116,  114,  119,
      121,  121,  120,  122,  122,  118,  115,  120,  123,  123,
      119,  124,  124,  125,  125,  128,  128,  129,  129,  127,
      127,  121,  126,  126,  122,  130,  130,  131,  131,  123,
      123,    0,  124,    0,  125,    0,  128,  125,  129,  121,
      127,  124,  122,  126,  126,  127,  130,    0,  131,  131,
      132,  132,  133,  133,  128,  134,  134,  135,  135,    0,
      136,  136,    0,    0,  130,    0,  137,  137,  138,  138,

        0,  132,    0,  133,    0,    0,  134,    0,  135,    0,
      132,  136,    0,  135,  139,  139,  136,  137,    0,  138,
      140,  140,  133,  141,  141,  134,  142,  142,    0,  143,
      143,    0,  144,  144,    0,  139,    0,  145,  145,  146,
      146,  140,  147,  147,  141,    0,  140,  142,    0,  141,
      143,    0,  142,  144,    0,  148,  148,  144,  145,    0,
      146,  149,  149,  147,  150,  150,  151,  151,    0,  152,
      152,  146,    0,  153,  153,  145,  148,  148,  154,  154,
        0,    0,  149,  147,    0,  150,    0,  151,  155,  155,
      152,  156,  156,    0,  153,  157,  157,  158,  158,  154,

        0,  149,  152,    0,  154,    0,  151,  153,    0,  155,
      159,  159,  156,    0,  155,    0,  157,    0,  158,  157,
        0,  158,  160,  160,  161,  161,  156,    0,  162,  162,
        0,  159,  163,  163,  165,  165,  164,  164,  167,  167,
      162,    0,    0,  160,    0,  161,  166,  166,  159,  162,
      168,  168,    0,  163,    0,  165,  160,  164,  164,  167,
        0,    0,  163,  169,  169,  170,  170,  166,  171,  171,
        0,  168,    0,  165,  172,  172,  173,  173,    0,  167,
        0,  166,  174,  174,  169,  168,  170,  175,  175,  171,
      176,  176,  177,  177,    0,  172,    0,  173,  178,  178,

      179,  179,    0,  174,  180,  180,  181,  181,  175,  182,
      182,  176,    0,  177,  185,  185,    0,  173,    0,  178,
      176,  179,  175,    0,  174,  180,  179,  181,  183,  183,
      182,    0,  184,  184,    0,  185,  180,    0,  178,  186,
      186,  187,  187,  189,  189,    0,  185,  188,  188,  183,
      183,    0,  181,  184,  190,  190,  191,  191,  192,  192,
      186,    0,  187,    0,  189,  193,  193,  189,  188,    0,
      184,  187,    0,  186,  188,  190,    0,  191,    0,  192,
      194,  194,  195,  195,  196,  196,  193,    0,  192,    0,
      197,  197,  190,    0,  191,  198,  198,    0,  199,  199,

        0,  194,    0,  195,    0,  196,  193,    0,  200,  200,
      194,  197,  201,  201,  196,    0,  198,    0,    0,  199,
        0,  198,  199,  202,  202,  203,  203,    0,  197,  200,
      204,  204,    0,  201,    0,  205,  205,    0,  200,  206,
      206,  207,  207,    0,  202,    0,  203,  205,  208,  208,
        0,  204,  209,  209,  210,  210,  205,    0,  211,  211,
      206,    0,  207,    0,  203,  212,  212,  207,  206,  208,
        0,  204,    0,  209,  208,  210,  213,  213,  209,  211,
      214,  214,  215,  215,  217,  217,  212,    0,  210,    0,
      211,    0,  216,  216,  218,  218,    0,  213,  219,  219,

      212,  214,    0,  215,    0,  217,  220,  220,  221,  221,
      217,    0,  214,  216,  213,  218,  215,  222,  222,  219,
      223,  223,  224,  224,  216,  225,  225,  220,    0,  221,
      226,  226,  219,  227,  227,  218,  228,  228,  222,  229,
      229,  223,    0,  224,    0,  220,  225,  230,  230,  222,
        0,  226,    0,    0,  227,  223,    0,  228,    0,  225,
      229,  224,    0,  226,  231,  231,  232,  232,  230,  233,
      233,  228,    0,  229,    0,  234,  234,  235,  235,  230,
        0,  236,  236,    0,    0,  231,    0,  232,    0,    0,
      233,    0,  237,  237,  238,  238,  234,    0,  235,  239,

      239,  235,  236,  236,  231,  240,  240,    0,  232,  234,
      241,  241,  233,  237,    0,  238,  242,  242,    0,  238,
      239,  243,  243,    0,  244,  244,  240,    0,  245,  245,
      237,  241,    0,    0,  240,  246,  246,  242,  247,  247,
        0,    0,  243,    0,  241,  244,  248,  248,    0,  245,
      244,    0,    0,  243,  245,    0,  246,    0,    0,  247,
      249,  249,  250,  250,  251,  251,    0,  248,  252,  252,
      253,  253,  247,  254,  254,  246,  255,  255,  248,  256,
      256,  249,    0,  250,    0,  251,  257,  257,    0,  252,
        0,  253,  258,  258,  254,  249,    0,  255,  251,    0,

      256,  252,  253,    0,  256,  259,  259,  257,  260,  260,
      261,  261,    0,  258,  262,  262,  255,  263,  263,    0,
      257,  264,  264,    0,  265,  265,  259,  267,  267,  260,
        0,  261,  266,  266,    0,  262,  268,  268,  263,  269,
      269,  263,  264,    0,  261,  265,  270,  270,  267,    0,
      271,  271,    0,  266,  262,    0,    0,  268,  265,  266,
      269,  272,  272,  273,  273,    0,    0,  270,  267,  274,
      274,  271,  275,  275,    0,  268,  270,  271,  276,  276,
        0,    0,  272,    0,  273,    0,  273,    0,  277,  277,
      274,  278,  278,  275,    0,  274,  279,  279,    0,  276,

      276,  272,  280,  280,    0,  276,  281,  281,  276,  277,
      282,  282,  278,  278,  283,  283,    0,  279,  284,  284,
      285,  285,    0,  280,  286,  286,    0,  281,  279,  287,
      287,  282,    0,    0,  280,  283,  282,    0,  281,  284,
        0,  285,  288,  288,    0,  286,  289,  289,  290,  290,
      287,  291,  291,  285,  283,  292,  292,    0,  284,  293,
      293,    0,    0,  288,  294,  294,    0,  289,    0,  290,
      295,  295,  291,  289,    0,    0,  292,  296,  296,    0,
      293,    0,  289,    0,    0,  294,  294,  297,  297,  298,
      298,  295,  299,  299,    0,  292,  295,    0,  296,  300,

      300,  301,  301,    0,  296,  302,  302,    0,  297,    0,
      298,    0,  297,  299,  303,  303,  304,  304,  299,    0,
      300,    0,  301,    0,  305,  305,  302,    0,  301,  306,
      306,  307,  307,  308,  308,  303,    0,  304,  309,  309,
      310,  310,  312,  312,  302,  305,  311,  311,  313,  313,
      306,    0,  307,    0,  308,  307,  305,  314,  314,  309,
        0,  310,  306,  312,    0,  308,    0,  311,    0,  313,
      315,  315,  309,  316,  316,    0,  311,    0,  314,    0,
      310,    0,  312,  317,  317,  318,  318,    0,  313,  319,
      319,  315,    0,    0,  316,  316,    0,  320,  320,    0,

      315,  321,  321,    0,  317,    0,  318,  322,  322,    0,
      319,  323,  323,  317,  324,  324,    0,  318,  320,  325,
      325,    0,  321,    0,  320,    0,    0,  319,  322,  326,
      326,    0,  323,  327,  327,  324,  328,  328,  329,  329,
      325,    0,    0,    0,    0,  325,  324,  322,  330,  330,
      326,  331,  331,    0,  327,  332,  332,  328,    0,  329,
      333,  333,  328,  326,  329,  327,  334,  334,    0,  330,
        0,    0,  331,    0,  330,    0,  332,  335,  335,  336,
      336,  333,  337,  337,  338,  338,    0,  334,  339,  339,
        0,  331,  334,  340,  340,    0,  332,    0,  335,    0,

      336,  336,  333,  337,    0,  338,  338,  341,  341,  339,
      342,  342,  343,  343,  340,  340,  344,  344,  345,  345,
      346,  346,  347,  347,  348,  348,    0,    0,  341,  349,
      349,  342,    0,  343,  350,  350,  342,  344,    0,  345,
        0,  346,  344,  347,  343,  348,    0,  346,  341,    0,
      349,  351,  351,  352,  352,  350,  353,  353,    0,  345,
      355,  355,  347,  356,  356,  348,  354,  354,  357,  357,
      358,  358,  351,  350,  352,  359,  359,  353,  361,  361,
        0,  355,  353,  352,  356,  351,    0,  354,  354,  357,
        0,  358,  360,  360,  362,  362,  359,  363,  363,  361,

      357,  359,  358,  364,  364,  365,  365,  366,  366,  367,
      367,  368,  368,  360,    0,  362,  360,    0,  363,  361,
      369,  369,    0,  363,  364,    0,  365,    0,  366,    0,
      367,    0,  368,  366,    0,  370,  370,  371,  371,  372,
      372,  369,  373,  373,  365,  374,  374,  375,  375,  376,
      376,  368,  377,  377,    0,  369,  370,    0,  371,    0,
      372,    0,    0,  373,  378,  378,  374,    0,  375,  370,
      376,  379,  379,  377,    0,  371,  380,  380,  377,  381,
      381,  375,  372,    0,  376,  378,  382,  382,  383,  383,
      384,  384,  379,  379,  385,  385,    0,  380,  378,    0,

      381,    0,  386,  386,    0,  387,  387,  382,    0,  383,
        0,  384,    0,  381,    0,  385,  388,  388,  389,  389,
      390,  390,  383,  386,  385,  382,  387,  391,  391,    0,
      384,  386,  392,  392,  393,  393,    0,  388,    0,  389,
        0,  390,  394,  394,    0,  387,  395,  395,  391,    0,
      388,  391,  389,  392,    0,  393,  396,  396,  397,  397,
      390,  398,  398,  394,  399,  399,    0,  395,    0,  400,
      400,    0,  392,  401,  401,  402,  402,  396,  396,  397,
      403,  403,  398,    0,  397,  399,  404,  404,    0,  399,
      400,  405,  405,    0,  401,    0,  402,  406,  406,  407,

      407,  403,  408,  408,    0,  409,  409,  404,    0,  400,
      404,    0,  405,  410,  410,  402,  411,  411,  406,    0,
      407,  412,  412,  408,    0,  405,  409,    0,    0,  407,
        0,  406,  413,  413,  410,  409,    0,  411,  414,  414,
      415,  415,  412,  416,  416,  417,  417,    0,  410,  418,
      418,    0,    0,  413,    0,    0,  411,  419,  419,  414,
        0,  415,    0,    0,  416,    0,  417,  420,  420,    0,
      418,    0,  413,  414,  415,  417,  421,  421,  419,  422,
      422,    0,  416,  418,  423,  423,  424,  424,  420,  425,
      425,  426,  426,  427,  427,    0,  419,  421,  429,  429,

      422,  428,  428,    0,    0,  423,    0,  424,    0,    0,
      425,  421,  426,    0,  427,  430,  430,    0,  422,  429,
      424,    0,  428,  428,  423,  431,  431,  432,  432,  426,
      433,  433,  427,  434,  434,    0,  430,    0,    0,    0,
        0,    0,    0,    0,    0,  430,  431,    0,  432,    0,
        0,  433,    0,    0,  434,    0,    0,    0,    0,  431,
        0,    0,    0,    0,    0,    0,    0,  432,    0,  433,
      438,  438,  439,    0,  439,  439,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,

      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435,  435,  435,  435,  435,  435,  435,  435,  435,  435,
      435
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[76] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define YY_NO_INPUT 1
#line 7 "lexer.l"
#include <iostream>
#include <cstdlib>
#include <vector>

#include "logical_expressions.h"
#include "rddl.h"

void lex_error(char c) {
    std::cerr << "\033[1;31mLexical ERROR! \033[0m Unknown char " << c
              << std::endl;
    exit(EXIT_FAILURE);
}

void yyerror (std::string message) {
    extern int yylineno;
    std::cerr << "\033[1;31mERROR! \033[0m Unknown token: " << yytext
              << " at line " << yylineno << ": "  << message << std::endl;
    exit(EXIT_FAILURE);
}

#include "parser.tab.hh"

#line 1133 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 35 "lexer.l"

#line 1351 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 436 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 2077 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "lexer.l"
{ return lessOrEqual_token; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "lexer.l"
{ return greaterOrEqual_token; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lexer.l"
{ return equal_token; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lexer.l"
{ return equivalent_token;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "lexer.l"
{ return imply_token;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "lexer.l"
{ return nonEqual_token; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexer.l"
{ return nonEqual_token; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "lexer.l"
{ return *yytext; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "lexer.l"
{ yylval.str = new std::string(yytext); return true_token;  }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "lexer.l"
{ yylval.str = new std::string(yytext); return false_token; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexer.l"
{ return domain_token; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexer.l"
{ return instance_token; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexer.l"
{ return objects_token; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexer.l"
{ return horizon_token; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "lexer.l"
{ return discount_token; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "lexer.l"
{ return init_state_token; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "lexer.l"
{ return requirements_token; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexer.l"
{ return state_action_constraints_token; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "lexer.l"
{ return action_preconditions_token; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "lexer.l"
{ return state_invariants_token; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "lexer.l"
{ return max_nondef_actions_token; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "lexer.l"
{ return terminate_when_token; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "lexer.l"
{ return types_token; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "lexer.l"
{ return variables_token; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "lexer.l"
{ return cpfs_token; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return cdfs_token; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "lexer.l"
{ return reward_token; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "lexer.l"
{ yylval.str = new std::string(yytext); return bool_token; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "lexer.l"
{ yylval.str = new std::string(yytext); return integer_token; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "lexer.l"
{ yylval.str = new std::string(yytext); return real_token; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "lexer.l"
{ yylval.str = new std::string(yytext); return object_token; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "lexer.l"
{ yylval.str = new std::string(yytext); return default_token; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "lexer.l"
{ yylval.str = new std::string(yytext); return level_token; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "lexer.l"
{ yylval.str = new std::string(yytext); return state_fluent_token; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "lexer.l"
{ yylval.str = new std::string(yytext); return intermediate_token; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "lexer.l"
{ yylval.str = new std::string(yytext); return non_fluent_token; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "lexer.l"
{ return non_fluents_token; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "lexer.l"
{ yylval.str = new std::string(yytext); return derived_fluent_token; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "lexer.l"
{ yylval.str = new std::string(yytext); return observ_fluent_token; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "lexer.l"
{ yylval.str = new std::string(yytext); return action_fluent_token; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return positive_infinity_token ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return negative_infinity_token ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return forall_token; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "lexer.l"
{ return exists_token; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "lexer.l"
{ return sum_token; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "lexer.l"
{ return product_token; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return product_token; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return if_token; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return then_token; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return else_token; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return switch_token; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return case_token; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return otherwise_token; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return kronDelta_token; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return diracDelta_token; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return uniform_token; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return bernoulli_token; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return discrete_token; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return normal_token; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return poisson_token; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return exponential_token; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return exponential_token; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return weibull_token; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return gama_token; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return multinomial_token; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return dirichlet_token; }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 102 "lexer.l"
{ /* Ignoring white spaces.*/}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 103 "lexer.l"
{ yylval.d = atof(yytext); return doubleNum_token;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 104 "lexer.l"
{ yylval.i = atoi(yytext); return intNum_token;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 105 "lexer.l"
{ yylval.str = new std::string(yytext); return id_token; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 106 "lexer.l"
{ yylval.str = new std::string(yytext); return variable_token; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 107 "lexer.l"
{ yylval.str = new std::string(yytext); return enum_token; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 108 "lexer.l"
{ /* Ignore comments. */}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 109 "lexer.l"
{ lex_error(*yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 110 "lexer.l"
ECHO;
	YY_BREAK
#line 1794 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 436 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 436 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 435);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 110 "lexer.l"


/* A Bison parser, made by GNU Bison 3.0.4.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

#ifndef YY_YY_PARSER_TAB_HH_INCLUDED
# define YY_YY_PARSER_TAB_HH_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    lessOrEqual_token = 258,
    greaterOrEqual_token = 259,
    negative_infinity_token = 260,
    equivalent_token = 261,
    imply_token = 262,
    equal_token = 263,
    nonEqual_token = 264,
    positive_infinity_token = 265,
    forall_token = 266,
    exists_token = 267,
    case_token = 268,
    if_token = 269,
    switch_token = 270,
    then_token = 271,
    else_token = 272,
    otherwise_token = 273,
    sum_token = 274,
    product_token = 275,
    kronDelta_token = 276,
    diracDelta_token = 277,
    uniform_token = 278,
    bernoulli_token = 279,
    discrete_token = 280,
    normal_token = 281,
    poisson_token = 282,
    exponential_token = 283,
    weibull_token = 284,
    gama_token = 285,
    dirichlet_token = 286,
    multinomial_token = 287,
    types_token = 288,
    variables_token = 289,
    cpfs_token = 290,
    cdfs_token = 291,
    reward_token = 292,
    domain_token = 293,
    requirements_token = 294,
    objects_token = 295,
    init_state_token = 296,
    state_action_constraints_token = 297,
    action_preconditions_token = 298,
    state_invariants_token = 299,
    instance_token = 300,
    non_fluents_token = 301,
    discount_token = 302,
    terminate_when_token = 303,
    horizon_token = 304,
    max_nondef_actions_token = 305,
    doubleNum_token = 306,
    id_token = 307,
    variable_token = 308,
    enum_token = 309,
    object_token = 310,
    integer_token = 311,
    real_token = 312,
    bool_token = 313,
    true_token = 314,
    false_token = 315,
    default_token = 316,
    level_token = 317,
    observ_fluent_token = 318,
    action_fluent_token = 319,
    state_fluent_token = 320,
    intermediate_token = 321,
    derived_fluent_token = 322,
    non_fluent_token = 323,
    intNum_token = 324,
    AgregateOperator = 325,
    NEGATIVE = 326
  };
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED

union YYSTYPE
{
#line 28 "parser.ypp" /* yacc.c:1909  */

    double d;
    int i;
    std::string* str;
    std::vector<std::string>* strs;

    RDDLTask* rddlTask;
    Parameter* parameter;
    std::vector<Parameter*>* parameters;
    ParameterList* parameterList;
    ParametrizedVariable* parametrizedVariable;
    std::vector<ParametrizedVariable*>* parametrizedVariables;
    LogicalExpression* logicalExpression;
    Type* type;
    std::vector<Type*>* types;
    std::vector<LogicalExpression*>* logicalExpressions;
    ConditionEffectPair* conditionEffect;
    std::vector<ConditionEffectPair*>* conditionEffects;
    DiscreteDistribution* lConstCaseList;

#line 147 "parser.tab.hh" /* yacc.c:1909  */
};

typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;

int yyparse (void);

#endif /* !YY_YY_PARSER_TAB_HH_INCLUDED  */

